package:
    name: mc_luigi
    version: "0.1"

source:
    git_url: https://github.com/constantinpape/mc_luigi
    git_tag: HEAD

build:
    number: 1
    string: py{{CONDA_PY}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

requirements:
    build:
        - python 2.7*
    run:
        - python 2.7*
        - h5py >=2.7
        - futures
        - luigi 2.1.1
        - vigra ==1.11.0.post222
        # we use nifty without cplex now TODO build conda package and specify version
        #- nifty-with-cplex ==0.4.post488
        - nifty
        - scikit-learn >=0.18.2

test:
    imports:
        - mc_luigi

about:
    license: BSD
    summary: Pipeline for large-scale neuro segmentation via Multicuts managed with luigi.
