package:
    name: mc_luigi
    version: "0.2"

source:
    git_url: https://github.com/constantinpape/mc_luigi
    git_tag: HEAD

build:
    number: 1
    string: py{{CONDA_PY}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

requirements:
    build:
        - python {{PY_VER}}*
    run:
        - python {{PY_VER}}*
        - h5py >=2.7
        - futures #[py2k]
        - luigi 2.3.0
        - vigra
        - scikit-learn
          # we use nifty without cplex now TODO specify version to get the stacked-rag version
        #- nifty-with-cplex ==0.4.post488
        - nifty

test:
    imports:
        - mc_luigi

about:
    license: MIT
    summary: Pipeline for large-scale neuro segmentation via Multicuts managed with luigi.
